### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by acikek** [nanokulonq/PrimalStage#5]
You need to initialize your color provider class in your client entrypoint.

[latest.log](https://github.com/nanokulonq/PrimalStage/files/11910387/latest.log)

**Comment by DadoIrie** [comment]
confirming the server crash during launch

```java
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'primalstage'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/ColorProviderRegistry
        at com.nanokulon.primalstage.init.ColorProvider.init(ColorProvider.java:9) ~[primalstage-1.1.0.jar:?]
        at com.nanokulon.primalstage.PrimalStage.onInitialize(PrimalStage.java:32) ~[primalstage-1.1.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.nanokulon.primalstage.init.ColorProvider.init(ColorProvider.java:9) ~[primalstage-1.1.0.jar:?]
        at com.nanokulon.primalstage.PrimalStage.onInitialize(PrimalStage.java:32) ~[primalstage-1.1.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 7 more
```

**Comment by nanokulonq** [comment]
fixed

**Comment by RyazhaKaslana** [comment]
Sorry to bother you, but it seems this issue still exists 
[2023-08-08-2.log](https://github.com/nanokulonq/PrimalStage/files/12291498/2023-08-08-2.log)

**Comment by acikek** [comment]
That's a different issue. Looks like you're missing Cloth Config.
